name: AmandAdam
favicon: null
layout_spectrum: 0.90202
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#c9bfbd'
    - '#b78b6e'
    - '#443123'
  brandStrength: 0.25
  lightness: 0.7732499474659562
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
